services:

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      # à décommenter à l'école :
      # - /home/nfordoxc/data/wordpress:/var/www/html
      - wordpress_data:/var/www/html
      - ../secrets:/run/secrets:ro
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception_network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "--no-check-certificate", "https://localhost/ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env 
    volumes:
      # à décommenter à l'école :
      # - /home/nfordoxc/data/wordpress:/var/www/html
      - wordpress_data:/var/www/html
      - ../secrets:/run/secrets:ro
    expose:
      - 9000
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "php", "-r", "if(!fsockopen('localhost', 9000)) exit(1);"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - REDIS_HOST=redis
    networks:
      - inception_network
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      # à décommenter à l'école :
      # - /home/nfordoxc/data/mariadb:/var/lib/mysql
      - mariadb_data:/var/lib/mysql
      - ../secrets:/run/secrets:ro
    expose:
      - 3306
    networks:
      - inception_network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    expose:
      - 6379
    networks:
      - inception_network
    restart: always

networks:
  inception_network:
    driver: bridge

# partie à supprimer à l'école
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
