services:

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      - /home/nfordoxc/data/wordpress:/var/www/html         # dans la vm
      # - wordpress_data:/var/www/html                      # surle mac
      # - /home/nicostrong/data/wordpress:/var/www/html     # sur le ubunmac
      - ../secrets:/run/secrets:ro
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
      portainer:
        condition: service_healthy
    networks:
      - inception_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost/ping"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env 
    volumes:
      - /home/nfordoxc/data/wordpress:/var/www/html         # dans la vm
      # - wordpress_data:/var/www/html                      # surle mac
      # - /home/nicostrong/data/wordpress:/var/www/html     # sur le ubunmac
      - ../secrets:/run/secrets:ro
    expose:
      - 9000
    depends_on:
      mariadb:
        condition: service_healthy
      adminer:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "-r", "if(!fsockopen('localhost', 9000)) exit(1);"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inception_network
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - /home/nfordoxc/data/mariadb:/var/lib/mysql        # dans la vm
      # - mariadb_data:/var/lib/mysql                     # sur le mac
      # - /home/nicostrong/data/mariadb:/var/lib/mysql    # sur ubunmac
      - ../secrets:/run/secrets:ro
    expose:
      - 3306
    networks:
      - inception_network
    restart: always
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "inception"]
      interval: 10s
      timeout: 5s
      retries: 5

  # BONUS SERVICES
  redis:
    build: ./requirements/redis
    container_name: redis
    env_file:
      - .env
    volumes:
      - /home/nfordoxc/data/redis:/data                   # sur la vm
      # - redis_data:/data                                # sur le mac
      # - /home/nicostrong/data/redis:/data               # sur ubunmac
      - ../secrets:/run/secrets:ro
    expose:
      - 6379
    networks:
      - inception_network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  vsftpd:
    build: ./requirements/vsftpd
    container_name: vsftpd
    env_file:
      - .env
    volumes:
      - /home/nfordoxc/data/wordpress:/var/www/html       # sur la vm
      # - wordpress_data:/var/www/html                    # sur le mac
      # - /home/nicostrong/data/wordpress:/var/www/html   # sur ubunmac
      - ../secrets:/run/secrets:ro
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: always
  
  adminer:
    build: ./requirements/adminer
    container_name: adminer
    env_file:
      - .env
    volumes:
      - ../secrets:/run/secrets:ro
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/adminer.php || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
  
  portainer:
    build: ./requirements/portainer
    container_name: portainer
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock             # socket de communication avec docker
      - /home/nfordoxc/data/portainer:/var/lib/portainer      # sur la vm
      # - portainer_data:/var/lib/portainer                   # sur le mac
      # - /home/nicostrong/data/portainer:/var/lib/portainer  # sur ubunmac
      - ../secrets:/run/secrets:ro
    ports:
      - "9443:9443"
    networks:
      - inception_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9010/api/status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  inception_network:
    driver: bridge

# to uncomment on mac
#volumes:
#  mariadb_data:
#    driver: local
#  wordpress_data:
#    driver: local
#  redis_data:
#    driver: local
#  portainer_data:
#    driver: local