services:

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
      - ../secrets:/run/secrets:ro
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: always
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env 
    volumes:
      - wordpress_data:/var/www/html
      - ../secrets:/run/secrets:ro
    expose:
      - 9000
    depends_on:
      - mariadb
    networks:
      - inception_network
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../secrets:/run/secrets:ro
    expose:
      - 3306
    networks:
      - inception_network
    restart: always

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
