services:

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      #- wordpress_data:/var/www/html to test on mac
      #- /home/nfordoxc/data/wordpress:/var/www/html  to uncomment at school
      - /home/nicostrong/data/wordpress:/var/www/html
      - ../secrets:/run/secrets:ro
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception_network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "--no-check-certificate", "https://localhost/ping"]
      interval: 10s
      timeout: 3s
      retries: 5
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env 
    volumes:
      #- wordpress_data:/var/www/html
      #- /home/nfordoxc/data/wordpress:/var/www/html  to uncomment at school
      - /home/nicostrong/data/wordpress:/var/www/html
      - ../secrets:/run/secrets:ro
    expose:
      - 9000
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "-r", "if(!fsockopen('localhost', 9000)) exit(1);"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inception_network
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      #- mariadb_data:/var/lib/mysql
      #- /home/nfordoxc/data/mariadb:/var/lib/mysql to uncomment at school
      - /home/nicostrong/data/mariadb:/var/lib/mysql
      - ../secrets:/run/secrets:ro
    expose:
      - 3306
    networks:
      - inception_network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  inception_network:
    driver: bridge

# partie a supprimer at school
#volumes:
#  mariadb_data:
#    driver: local
#  wordpress_data:
#    driver: local
