services:
  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    #depends_on:
    #  - wordpress
    networks:
      - inception_network
    restart: always
#
#  wordpress:
#    build: ./srcs/requirements/wordpress
#    container_name: wordpress
#    environment:
#      WORDPRESS_DB_HOST: mariadb
#      WORDPRESS_DB_USER: "${DB_USER}"
#      WORDPRESS_DB_NAME: "${DB_NAME}"
#    volumes:
#      - wordpress_data:/var/www/html
#    secrets:
#      - db_password
#      - wp_settings
#    depends_on:
#      - mariadb
#    expose:
#      - 9000
#    networks:
#      - inception_network
#    restart: always
#
#  mariadb:
#    build: ./srcs/requirements/mariadb
#    container_name: mariadb
#    environment:
#      MYSQL_DATABASE: "${DB_NAME}"
#      MYSQL_USER: "${DB_USER}"
#    volumes:
#      - mariadb_data:/var/lib/mysql
#    secrets:
#      - db_root_password
#      - db_password
#    networks:
#      - inception_network
#    restart: always
#
networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt
  wp_settings:
    file: secrets/wp_settings.txt

