version: "3.8"

services:
  nginx:
    image: 42_luxembourg_inception_nginx:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  wordpress:
    image: 42_luxembourg_inception_wordpress:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - wp_host
      - wp_admin
      - wp_pwd
      - wp_mail
      - db_name
      - db_host
      - db_user
      - db_pwd
    expose:
      - 9000
    networks:
      - inception_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
  mariadb:
    image: 42_luxembourg_inception_mariadb:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_name
      - db_user
      - db_pwd
      - db_root_pwd
    expose:
      - 3306
    networks:
      - inception_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  inception_network:
    driver: overlay

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

secrets:
  db_name:
    file: secrets/db_name.txt
  db_user:
    file: secrets/db_user.txt
  db_pwd:
    file: secrets/db_pwd.txt
  db_root_pwd:
    file: secrets/db_root_pwd.txt
  wp_admin:
    file: secrets/wp_admin.txt
  wp_host:
    file: secrets/wp_host.txt
  wp_mail:
    file: secrets/wp_mail.txt
  wp_pwd:
    file: secrets/wp_pwd.txt