version:  '3.8'

services:
  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT}:443"
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_password
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: always

  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD_FILE: "${DB_PASSWORD_FILE}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_password
    depends_on:
      - mariadb
    networks:
      - inception_network
    restart: always

  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD_FILE}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD_FILE}"
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception_network
    restart: always

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secretrs/db_root_password.txt

