version: "3.8"

services:
  mariadb:
    build: ./srcs/requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./secrets:/run/secrets:ro
    expose:
      - 3306
    networks:
      - inception_network

  wordpress:
    build: ./srcs/requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./secrets:/run/secrets:ro
    expose:
      - 9000
    depends_on:
      - mariadb
    networks:
      - inception_network

  nginx:
    build: ./srcs/requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - ./secrets:/run/secrets:ro
    depends_on:
      - wordpress
    networks:
      - inception_network
networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
