version: "3.8"

services:
  nginx:
    image: 42_luxembourg_inception_nginx:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network

  wordpress:
    image: 42_luxembourg_inception_wordpress:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_host
      - db_user
      - db_name
      - db_password
      - wp_admin
      - wp_host
      - wp_mail
      - wp_password
      - wp_port
    expose:
      - 9000
    networks:
      - inception_network

  mariadb:
    image: 42_luxembourg_inception_mariadb:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_name
      - db_user
      - db_root_password
      - db_password
    networks:
      - inception_network

networks:
  inception_network:
    driver: overlay

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

secrets:
  db_host:
    file: secrets/db_host.txt
  db_name:
    file: secrets/db_name.txt
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt
  db_user:
    file: secrets/db_user.txt
  wp_admin:
    file: secrets/wp_admin.txt
  wp_host:
    file: secrets/wp_host.txt
  wp_mail:
    file: secrets/wp_mail.txt
  wp_password:
    file: secrets/wp_password.txt
  wp_port:
    file: secrets/wp_port.txt

