FROM alpine:3.21

#   update and upgrade of apk
RUN apk update && apk upgrade

#   installing some programs
RUN apk add --no-cache	redis
RUN apk add --no-cache	bash

#   creating some directory
RUN mkdir -p			/scripts
RUN mkdir -p			/data

#	copy config file
COPY					conf/redis.conf /etc/redis/redis.conf
COPY					tools/entrypoint.sh /scripts/entrypoint.sh

#   put right
RUN chmod +x			/scripts/entrypoint.sh

ENTRYPOINT [ "/scripts/entrypoint.sh" ]