#   os of the container not the latest
FROM alpine:3.21

#   update and upgrade of apk
RUN apk update && apk upgrade

#   installing some programs
RUN apk add --no-cache		nginx
RUN apk add --no-cache		openssl
RUN apk add --no-cache		bash
RUN apk add --no-cache		curl
RUN apk add --no-cache		vim

#   creating some directory
RUN mkdir -p 				/var/log/nginx
RUN mkdir -p 				/var/run/nginx
RUN mkdir -p 				/var/www/html
RUN mkdir -p 				/etc/nginx/ssl
RUN mkdir -p 				/scripts

#   creating some empty files
RUN touch					/var/log/nginx/access.log
RUN touch					/var/log/nginx/error.log

#   creating new user and new group if not exist
RUN deluser                         www-data || true
RUN delgroup                        www-data || true
RUN addgroup -g                     33 www-data
RUN adduser -S -H -D -u             33 -G www-data www-data

#   put right
RUN chown -R				root:root /var/log/nginx
RUN chown -R				root:root /etc/nginx/ssl
RUN chown -R				www-data:www-data /var/www/html
RUN chmod 755				/var/www/html

#   copy config file for nginx
COPY conf/nginx.conf		/etc/nginx/nginx.conf

#   copy script file for sshkey and entrypoint
COPY tools/generate_ssl.sh	/scripts/generate_ssl.sh
COPY tools/entrypoint.sh	/scripts/entrypoint.sh

#   alow execution ok all scripts
RUN chmod +x				/scripts/*.sh

#   entrypoint of the container
ENTRYPOINT ["/scripts/entrypoint.sh"]