FROM alpine:latest

RUN apk update && apk add --no-cache nginx openssl bash curl

RUN mkdir -p /var/log/nginx \
 && mkdir -p /etc/nginx/ssl \
 && mkdir -p /scripts \
 && touch /var/log/nginx/access.log /var/log/nginx/error.log \
 && chown -R root:root /etc/nginx/ssl /var/log/nginx

COPY conf/nginx.conf /etc/nginx/nginx.conf

COPY tools/generate_ssl.sh /scripts/generate_ssl.sh
COPY tools/entrypoint.sh /scripts/entrypoint.sh

RUN chmod +x /scripts/*.sh

ENTRYPOINT ["/scripts/entrypoint.sh"]
